<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! current_user_can( 'manage_options' ) ) {
    wp_die( esc_html__( 'You do not have permission.', 'backoffice-manager-for-firebase' ) );
}
?>

<div class="wrap bomff-wrap">
  <h1><?php esc_html_e( 'Firestore', 'backoffice-manager-for-firebase' ); ?></h1>

  <div id="firebase-admin-panel-app">

    <div class="bomff-section">
      <p><?php esc_html_e( 'Firebase status:', 'backoffice-manager-for-firebase' ); ?> <span id="firebase-connection-status"><?php esc_html_e( 'Loading…', 'backoffice-manager-for-firebase' ); ?></span></p>
      <p><?php esc_html_e( 'Authentication status:', 'backoffice-manager-for-firebase' ); ?> <span id="firebase-auth-status"><?php esc_html_e( 'Checking…', 'backoffice-manager-for-firebase' ); ?></span></p>
    </div>

    <!-- GUIDED CREATION -->
    <div class="bomff-section bomff-mt-20">
      <h2><?php esc_html_e( 'Guided creation', 'backoffice-manager-for-firebase' ); ?></h2>

      <div class="bomff-structure-box">
        <p class="bomff-mt-0">
          <?php
          echo wp_kses_post(
            __( 'A <strong>structure</strong> defines which fields are used to <strong>create</strong> new documents using a guided form.', 'backoffice-manager-for-firebase' )
          );
          ?>
        </p>
        <p class="bomff-mt-0">
          <?php
          echo wp_kses_post(
            __( 'It is generated by analyzing documents from an existing <strong>collection</strong> in Firestore (it does not create collections or invent fields).', 'backoffice-manager-for-firebase' )
          );
          ?>
        </p>

        <div class="bomff-controls">
          <button id="bomff-import-structure" class="button button-secondary" type="button">
            <?php esc_html_e( 'Import structure from collection', 'backoffice-manager-for-firebase' ); ?>
          </button>

          <button id="bomff-view-structure" class="button" type="button" disabled>
            <?php esc_html_e( 'View structure', 'backoffice-manager-for-firebase' ); ?>
          </button>

          <button id="bomff-create-doc" class="button button-primary" type="button" disabled>
            <?php esc_html_e( 'Create document', 'backoffice-manager-for-firebase' ); ?>
          </button>

          <button id="bomff-delete-structure" class="button" type="button" disabled>
            <?php esc_html_e( 'Delete structure', 'backoffice-manager-for-firebase' ); ?>
          </button>
		  
		  <?php do_action( 'bomff_firestore_guided_toolbar_end' ); ?>
        </div>

        <p id="bomff-structure-msg" class="bomff-msg-top"></p>

        <div id="bomff-structure-mini" class="bomff-mt-10 bomff-hidden">
          <span><strong><?php esc_html_e( 'Collection:', 'backoffice-manager-for-firebase' ); ?></strong> <code id="bomff-structure-collection"></code></span>
          &nbsp;—&nbsp;
          <span><strong><?php esc_html_e( 'Fields:', 'backoffice-manager-for-firebase' ); ?></strong> <span id="bomff-structure-count"></span></span>
        </div>
      </div>
    </div>

    <!-- EXPLORER -->
    <div class="bomff-section bomff-mt-20">
      <h2><?php esc_html_e( 'Explore a collection', 'backoffice-manager-for-firebase' ); ?></h2>

      <div class="bomff-controls">
        <input
          type="text"
          id="bomff-collection-name"
          placeholder="<?php echo esc_attr__( 'e.g. affiliates', 'backoffice-manager-for-firebase' ); ?>"
        />

        <select id="bomff-page-size" aria-label="<?php echo esc_attr__( 'Page size', 'backoffice-manager-for-firebase' ); ?>">
          <option value="25">25</option>
          <option value="50">50</option>
          <option value="100">100</option>
        </select>

        <button id="bomff-load-collection" class="button button-primary" type="button">
          <?php esc_html_e( 'Load', 'backoffice-manager-for-firebase' ); ?>
        </button>

        <button id="bomff-clear-results" class="button" type="button">
          <?php esc_html_e( 'Clear', 'backoffice-manager-for-firebase' ); ?>
        </button>
		
		<?php do_action( 'bomff_firestore_explorer_toolbar_end' ); ?>
      </div>

      <div class="bomff-controls-row">
        <input
          type="text"
          id="bomff-doc-id"
          placeholder="<?php echo esc_attr__( 'Doc ID (optional)', 'backoffice-manager-for-firebase' ); ?>"
        />
        <button id="bomff-load-doc" class="button" type="button">
          <?php esc_html_e( 'Load document', 'backoffice-manager-for-firebase' ); ?>
        </button>
      </div>

      <p id="bomff-collection-msg"></p>
    </div>

    <div class="bomff-section bomff-my-10">
      <button id="bomff-prev-page" class="button" type="button" disabled><?php esc_html_e( '◀ Prev', 'backoffice-manager-for-firebase' ); ?></button>
      <button id="bomff-next-page" class="button" type="button" disabled><?php esc_html_e( 'Next ▶', 'backoffice-manager-for-firebase' ); ?></button>
    </div>

    <div class="bomff-section">
      <div class="bomff-table-scroll">
        <table class="widefat striped" id="bomff-results-table">
          <thead>
            <tr id="bomff-results-head-row">
              <th><?php esc_html_e( 'Doc ID', 'backoffice-manager-for-firebase' ); ?></th>
              <th><?php esc_html_e( 'Fields', 'backoffice-manager-for-firebase' ); ?></th>
              <th class="bomff-col-actions"><?php esc_html_e( 'Actions', 'backoffice-manager-for-firebase' ); ?></th>
            </tr>
          </thead>
          <tbody id="bomff-collection-results">
            <tr>
              <td colspan="3" class="bomff-center-muted">
                <?php esc_html_e( 'Enter a collection and click “Load”.', 'backoffice-manager-for-firebase' ); ?>
              </td>
            </tr>
          </tbody>
        </table>
		
		<?php do_action( 'bomff_firestore_after_results_table' ); ?>
      </div>
    </div>

  </div>
</div>

<!-- JSON MODAL -->
<div id="bomff-json-modal" class="bomff-modal" aria-hidden="true">
  <div class="bomff-modal__panel" role="dialog" aria-modal="true" aria-labelledby="bomff-json-title">
    <div class="bomff-modal__header">
      <h2 id="bomff-json-title"><?php esc_html_e( 'Firestore document', 'backoffice-manager-for-firebase' ); ?></h2>
      <button id="bomff-close-json-x" class="button" type="button">✕</button>
    </div>
    <div class="bomff-modal__body">
      <pre id="bomff-json-content" class="bomff-json-pre"></pre>
    </div>
    <div class="bomff-modal__footer">
      <button id="bomff-copy-json" class="button" type="button"><?php esc_html_e( 'Copy', 'backoffice-manager-for-firebase' ); ?></button>
      <button id="bomff-download-json" class="button" type="button"><?php esc_html_e( 'Download', 'backoffice-manager-for-firebase' ); ?></button>
      <button id="bomff-close-json" class="button button-primary" type="button"><?php esc_html_e( 'Close', 'backoffice-manager-for-firebase' ); ?></button>
    </div>
  </div>
</div>

<!-- EDIT DOCUMENT MODAL -->
<div id="bomff-edit-modal" class="bomff-modal" aria-hidden="true">
  <div class="bomff-modal__panel" role="dialog" aria-modal="true" aria-labelledby="bomff-edit-title">
    <div class="bomff-modal__header">
      <h2 id="bomff-edit-title"><?php esc_html_e( 'Edit document', 'backoffice-manager-for-firebase' ); ?></h2>
      <button id="bomff-edit-close-x" class="button" type="button">✕</button>
    </div>
    <div class="bomff-modal__meta">
      <div><strong><?php esc_html_e( 'Collection:', 'backoffice-manager-for-firebase' ); ?></strong> <code id="bomff-edit-collection"></code></div>
      <div><strong><?php esc_html_e( 'Doc ID:', 'backoffice-manager-for-firebase' ); ?></strong> <code id="bomff-edit-docid"></code></div>
    </div>
    <div class="bomff-modal__body">
      <form id="bomff-edit-form" class="bomff-modal__form">
        <div class="bomff-field">
          <label for="bomff-edit-json"><?php esc_html_e( 'JSON', 'backoffice-manager-for-firebase' ); ?></label>
          <textarea id="bomff-edit-json" rows="16" spellcheck="false" class="bomff-code-textarea"></textarea>
          <div id="bomff-edit-error" class="bomff-hint-error bomff-hidden"></div>
          <div class="bomff-muted">
            <?php esc_html_e( 'Edit the full JSON content of the document. Be careful with commas, quotes, and data types.', 'backoffice-manager-for-firebase' ); ?>
          </div>
        </div>
      </form>
    </div>
    <div class="bomff-modal__footer">
      <button id="bomff-edit-cancel" class="button" type="button"><?php esc_html_e( 'Close', 'backoffice-manager-for-firebase' ); ?></button>
      <button id="bomff-edit-save" class="button button-primary" type="button"><?php esc_html_e( 'Save changes', 'backoffice-manager-for-firebase' ); ?></button>
    </div>
  </div>
</div>

<!-- IMPORT STRUCTURE MODAL -->
<div id="bomff-structure-modal" class="bomff-modal" aria-hidden="true">
  <div class="bomff-modal__panel" role="dialog" aria-modal="true" aria-labelledby="bomff-structure-title">
    <div class="bomff-modal__header">
      <h2 id="bomff-structure-title"><?php esc_html_e( 'Import structure', 'backoffice-manager-for-firebase' ); ?></h2>
      <button id="bomff-structure-close-x" class="button" type="button">✕</button>
    </div>
    <div class="bomff-modal__meta">
      <div>
        <?php
        echo wp_kses_post(
          __( 'Up to <strong>25 documents</strong> from the selected collection will be analyzed to detect fields and types.', 'backoffice-manager-for-firebase' )
        );
        ?>
      </div>
    </div>
    <div class="bomff-modal__body">
      <p class="bomff-mt-0">
        <strong><?php esc_html_e( 'Collection:', 'backoffice-manager-for-firebase' ); ?></strong> <code id="bomff-structure-modal-collection"></code>
      </p>

      <div id="bomff-structure-detected" class="bomff-structure-fields"></div>

      <p class="bomff-muted bomff-mt-10">
        <?php
        echo wp_kses_post(
          __( 'Tip: keep checked the fields you want to fill when creating documents. “Auto” fields are filled automatically.', 'backoffice-manager-for-firebase' )
        );
        ?>
      </p>
    </div>
    <div class="bomff-modal__footer">
      <button id="bomff-structure-cancel" class="button" type="button"><?php esc_html_e( 'Cancel', 'backoffice-manager-for-firebase' ); ?></button>
      <button id="bomff-structure-save" class="button button-primary" type="button" disabled><?php esc_html_e( 'Save structure', 'backoffice-manager-for-firebase' ); ?></button>
    </div>
  </div>
</div>

<!-- ACTIVE STRUCTURE VIEW MODAL -->
<div id="bomff-structure-view-modal" class="bomff-modal" aria-hidden="true">
  <div class="bomff-modal__panel" role="dialog" aria-modal="true" aria-labelledby="bomff-structure-view-title">
    <div class="bomff-modal__header">
      <h2 id="bomff-structure-view-title"><?php esc_html_e( 'Active structure', 'backoffice-manager-for-firebase' ); ?></h2>
      <button id="bomff-structure-view-close-x" class="button" type="button">✕</button>
    </div>
    <div class="bomff-modal__meta">
      <div><strong><?php esc_html_e( 'Collection:', 'backoffice-manager-for-firebase' ); ?></strong> <code id="bomff-structure-view-collection"></code></div>
      <div class="bomff-muted">
        <?php esc_html_e( 'This structure is used to generate the “Create document” form.', 'backoffice-manager-for-firebase' ); ?>
      </div>
    </div>
    <div class="bomff-modal__body">
      <div id="bomff-structure-view-fields" class="bomff-structure-fields"></div>
    </div>
    <div class="bomff-modal__footer">
      <button id="bomff-structure-view-close" class="button button-primary" type="button"><?php esc_html_e( 'Close', 'backoffice-manager-for-firebase' ); ?></button>
    </div>
  </div>
</div>

<!-- CREATE DOCUMENT MODAL -->
<div id="bomff-create-modal" class="bomff-modal" aria-hidden="true">
  <div class="bomff-modal__panel" role="dialog" aria-modal="true" aria-labelledby="bomff-create-title">
    <div class="bomff-modal__header">
      <h2 id="bomff-create-title"><?php esc_html_e( 'Create document', 'backoffice-manager-for-firebase' ); ?></h2>
      <button id="bomff-create-close-x" class="button" type="button">✕</button>
    </div>
    <div class="bomff-modal__meta">
      <div><strong><?php esc_html_e( 'Collection:', 'backoffice-manager-for-firebase' ); ?></strong> <code id="bomff-create-collection"></code></div>
      <div class="bomff-muted"><?php esc_html_e( 'A new document will be created with an auto-generated ID.', 'backoffice-manager-for-firebase' ); ?></div>
    </div>
    <div class="bomff-modal__body">
      <form id="bomff-create-form" class="bomff-modal__form">
        <div id="bomff-create-fields"></div>
        <div id="bomff-create-error" class="bomff-hint-error bomff-hidden"></div>
      </form>
    </div>
    <div class="bomff-modal__footer">
      <button id="bomff-create-cancel" class="button" type="button"><?php esc_html_e( 'Close', 'backoffice-manager-for-firebase' ); ?></button>
      <button id="bomff-create-save" class="button button-primary" type="button"><?php esc_html_e( 'Create', 'backoffice-manager-for-firebase' ); ?></button>
    </div>
  </div>
</div>
